### ISSUE TITLE
Using different/custom version of Apache Flink

### ISSUE THREAD

**Issue by mnoumanshahzad** [peelframework/peel#110]
Hi,
  I am trying to benchmark a custom Apache Flink build and Apache Flink v1.1.4. Apparently the current Peel Framework code runs experiments on Apache Flink v1.1 Can you kindly point out the changes I need to make in the project to be able to use the other versions of Apache Flink.

Thanks

**Comment by aalexandrov** [comment]
@mnoumanshahzad We can certainly help.

The lasest version of Peel [added support for Flink v1.1.4](https://github.com/peelframework/peel/commit/3484d2888134c457254502f59e6427fe172e6999).

To migrate to Flink v1.1.4 you have to:

## 1. Update Peel

First you need to update the `peel-core` and `peel-extensions` versions used in your project. To do this, change the `peel.version` to `1.1.4` in your main `pom.xml` (FYI, the fact that the Flink version you want to use and the Peel version you have to use to get it coincide is a pure coincidence).

To verify that this works, re-build the project

```bash
rm -Rf $BUNDLE_BIN/$BUNDLE_NAME/lib
mvn clean deploy -Pdev
```

and then from the `$BUNDLE_BIN/$BUNDLE_NAME` run

```bash
./peel.sh sys:setup flink-1.1.4
```

At this point Flink 1.1.4 should be up and running on your developer machine.

## 2. Possibly Redefine the Flink 1.1.4 Bean

The latest version of `peel-extensions` already [contains a definition of a `flink-1.1.4` bean](https://github.com/peelframework/peel/blob/3484d2888134c457254502f59e6427fe172e6999/peel-extensions/src/main/scala/org/peelframework/extensions.scala#L210-L216) that you can use in your [Experiments Definitions](http://peel-framework.org/manual/experiments-definitions.html).

However, in case in your bundle defines experiments where Flink always depends on other systems (e.g. HDFS or Zookeeper), chances are you will find a file called `systems.scala` (if you use Scala-based) configuration, or in your `systems.xml` (if you use an XML-based configuration) that overrides the `flink-1.1` bean definition in order to add the additional system dependencies. If this is the case, replicate the code snippet and adapt it in order to override the `flink-1.1.4` bean definition in a similar manner.

## 3. Adapt The Experiment Definitions

In your experiments definition, refer to `flink-1.1.4` as the Experiment `runner`, e.g. in Scala the syntax will be

```scala
runner = ctx.getBean("flink-1.1.4", classOf[Fli])
```

whereas before it was
